config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'questions#index'

  resource :users, only: [ :new, :create ]
  resource :sessions, only: [:new, :create]
end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password validations: false

  validates :username, presence: true, uniqueness: true
  validates :password, presence: true, on: :create

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create

  user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])

      session[:user_id] = user.id
      flash[:notice] = 'You have logged in'
      redirect_to root_path
    else
      flash[:error] = 'there is something wrong with yr log info'
      render :new

    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'Thanks for registering'
      redirect_to root_path
    else
      render :new
    end

  end
  private

  def user_params
    params.require(:user).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/common/_form_errors.html.haml
- if object.errors.any?
  .row
    .alert.alert-error.span8
      %h5 Please fix the following errors:
      %ul
      - object.errors.full_messages.each do |msg|
        %li= msg

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  %div(class="alert alert-#{name}")
    %a.close(data-dismiss='alert') &#215;
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/layouts/_navigation.html.haml
%ul.nav
  %li
    = link_to "Post something here", root_path, :class => 'brand'
  %li
    = link_to 'Register', new_users_path
    = link_to 'Log in', new_sessions_path

app/views/layouts/application.html.haml
!!!%html  %head    %meta{charset: "utf-8"}/    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/    %title Tealeaf Academy - Postit    %meta{content: "", name: "description"}/    %meta{content: "", name: "author"}/    = stylesheet_link_tag "application", :media => "all"    = javascript_include_tag "application"    = csrf_meta_tags    = yield(:head)  %body    %header      .navbar        .navbar-inner          .container            = render 'layouts/navigation'    #main{role: "main"}      .container        .row          .span12            = render 'layouts/messages'            = yield        %footer      / ! end of .container    / ! end of #main

app/views/posts/index.html.erb
<h3>Welcome!</h3>

<p>This is the Postit template. You've access the PostsController, index action. This is the index template. Find me under app/views/posts folder.</p>

app/views/questions/index.html.erb
something

app/views/users/new.html.haml
%section.register.container
= form_for(@user) do |f|
  = render 'common/form_errors', object: @user
  %header
    %h1 Log in
  %fielset
    = f.label :username
    = f.text_field :username
    = f.label :password
    = f.password_field :password
  %fieldset.action
    = f.submit 'login', class: 'btn btn-success'